name: dart_console_app
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

dependencies:
  convert: ^3.1.2
  crypto: ^3.0.6
  cryptography: ^2.7.0
  ed25519_edwards: ^0.3.1
  hex: ^0.2.0
  path: ^1.9.1
  pinenacl: ^0.6.0
  solana: ^0.31.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
