name: ed25519_nacl
description: A port of the TweetNaCl Javascript library to Dart together with an implementation that creates an ED25519 sub key from an EVM public key.
version: 1.0.0
repository: https://github.com/STLResearch/ed25519_nacl

environment:
  sdk: ^3.4.4

dependencies:
  convert: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
